spring.application.name=LAP

spring.datasource.url=jdbc:postgresql://localhost:5432/loan_db
spring.datasource.username=admin
spring.datasource.password=password

# Turnin off Hibernate  bcs we gonna do Migrations
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Settings for Swagger
springdoc.swagger-ui.path=/swagger-ui.html